### PR TITLE
Switch to snap-plugin-lib-go

### PR DESCRIPTION
**Pull request by denismakogon**
Switching from snap/core and snap/plugin to snap-plugin-lib-go

Summary of changes:
- updating glide with new dependency
- changing imports wherever it is necessary

### CODE REVIEW

**Comment by denismakogon** [comment]
@kindermoumoute i'm not able to say that this code works because i've faced with problem that i'm not capable to overcome:
```
ubuntu@ubuntu:/opt/stack/functions/src/github.com/intelsdi-x/snap-plugin-collector-docker$ make all
bash -c "./scripts/build.sh /opt/stack/functions/src/github.com/intelsdi-x/snap-plugin-collector-docker"
2016-12-21 14:52:32 UTC [     info] project path: /opt/stack/functions/src/github.com/intelsdi-x/snap-plugin-collector-docker
2016-12-21 14:52:32 UTC [     info] plugin name: snap-plugin-collector-docker
2016-12-21 14:52:32 UTC [     info] building plugin: snap-plugin-collector-docker
# github.com/intelsdi-x/snap-plugin-collector-docker/vendor/github.com/intelsdi-x/snap-plugin-lib-go/v1/plugin/rpc
vendor/github.com/intelsdi-x/snap-plugin-lib-go/v1/plugin/rpc/plugin.pb.go:768: undefined: grpc.SupportPackageIsVersion3
Makefile:37: recipe for target 'all' failed
make: *** [all] Error 1
```

Can you provide any help on it?

**Comment by nanliu** [comment]
@denismakogon, please rebase your PR against the current master, and use the command `glide update`  to resolve the new dependencies. There will be some of the changes required by the new plugin lib, but the error message will be much more informative. Most of them should be along the lines of updating ` mt.Namespace().String()` to ` mt.Namespace.String()`.

**Comment by denismakogon** [comment]
@kindermoumoute ready for review.

**Comment by marcin-krolik** [comment]
LGTM

As the side note, I'm currently working on heavy refactoring of docker collector. 
First, no more expensive collects for metrics which are not requested. Additionally, it will recognize cgroupfs diver properly. Last but not least is removal of dependency to openlibcontainers/runc.

**Pull request merged**
